services:
  magic:
    image: mageai/mageai:latest
    command: >
      bash -c "pip install -r /home/src/requirements.txt && mage start ${PROJECT_NAME}"
    env_file:
      - .env
    # command: mage start ${PROJECT_NAME}
    # env_file:
    #   - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
    networks:
      - app-network

  mlflow:
    build:
      context: .
      dockerfile: mlflow.dockerfile
    ports:
      - "5050:5050"
    volumes:
      - "${PWD}/mlflow_data:/home/mlflow_data/"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
